### ISSUE TITLE
Further discussion from deleted repo

### ISSUE THREAD

**Issue by androidacy-user** [bromite/bromitewebview#4]
What remains to be resolved?

And can I have write access to the repository?

**Comment by csagan5** [comment]
@alexa-v2 there will not be an official module, see the other conversation.

I will delete this repository in a few days.

**Comment by androidacy-user** [comment]
See my comments in the other conversation

I do not believe this to be the death of this idea; I will just have to work harder to make it happen. Already have a script to commit/push changes, wouldn't be hard to push here in it as well as the magisk repo

**Comment by androidacy-user** [comment]
I need write access to this repository @csagan5

**Comment by androidacy-user** [comment]
@csagan5 you've been granted write access to the magisk hosted repo, if I can get write access to the Bromite hosted repo I'll update my build script to push to both magisk and Bromite repo at once

The last 5 commit from magisk need merged into Bromite. I had to temporarily re-add prebuilt curl binaries until we can figure out building from sources

**Comment by csagan5** [comment]
@alexa-v2 disagree; we are not going to use prebuilt curl binaries of unknown sources.

**Comment by alexa-v2** [comment]
@csagan the alternative is to **completely** break the module until we figure that out, remember it downloaded the app separate

**Comment by androidacy-user** [comment]
@csagan5 the alternative is to **completely** break the module until we figure that out, remember it downloaded the app separate

**Comment by androidacy-user** [comment]
As I said it's a **temporary** fix to get it working

**Comment by csagan5** [comment]
@alexa-v2 I see you have already forked from this repository; that is fine.

I will however not accept the invitation to that repository or yours because we have radically different views on security and how things should be managed.

I suggest that you keep maintaining the module as you did before, although it is not officially endorsed for the reasons stated above which are not negligible.

Feel free to submit PRs to this repository with your improvements (except `curl` and other binaries, which I will not accept).

**Comment by androidacy-user** [comment]
I would be happy to work out our differences here

You must understand however I needed to get the module working, and **not** after hours of fighting with building curl from source

**Comment by androidacy-user** [comment]
And I'd be happy to hear out your views on "security and management"
